[project]
name = 'substack-protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.subscription-vault]
path = 'contracts/subscription-vault.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-plans]
path = 'contracts/subscription-plans.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-engine]
path = 'contracts/subscription-engine.clar'
clarity_version = 3
epoch = 'latest'
depends_on = ['subscription-vault', 'subscription-plans']

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'