[project]
name = 'substack-protocol'
description = 'Trustless recurring payments on Stacks'
authors = []
telemetry = false
cache_dir = '.\.cache'

[contracts.subscription-vault]
path = 'contracts/subscription-vault.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-plans]
path = 'contracts/subscription-plans.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-engine]
path = 'contracts/subscription-engine.clar'
clarity_version = 3
epoch = 'latest'
depends_on = ['subscription-vault', 'subscription-plans']

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false